#!/usr/bin/env python3
"""Write text content into common document formats (docx, xlsx, pptx, pdf).

Usage:
    python scripts/write_document.py <output_path> [--input <text_file>] [--title <title>]

Reads text from stdin (or --input file) and writes to the specified format.

Supported output formats: .docx, .xlsx, .pptx, .pdf
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path


def write_docx(path: Path, text: str, title: str) -> None:
    """Write text into a .docx document."""
    from docx import Document

    doc = Document()
    doc.add_heading(title, level=0)
    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("## "):
            doc.add_heading(stripped[3:], level=2)
        elif stripped.startswith("# "):
            doc.add_heading(stripped[2:], level=1)
        elif stripped.startswith("- "):
            doc.add_paragraph(stripped[2:], style="List Bullet")
        elif stripped:
            doc.add_paragraph(stripped)
    doc.save(str(path))


def write_xlsx(path: Path, text: str, title: str) -> None:
    """Write text into a .xlsx spreadsheet (one row per line)."""
    from openpyxl import Workbook

    wb = Workbook()
    ws = wb.active
    ws.title = title[:31]  # Excel limits sheet names to 31 chars
    ws.append(["Line", "Content"])
    for idx, line in enumerate(text.split("\n"), 1):
        ws.append([idx, line])
    wb.save(str(path))


def write_pptx(path: Path, text: str, title: str) -> None:
    """Write text into a .pptx presentation."""
    from pptx import Presentation

    prs = Presentation()

    # Title slide
    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = title
    title_slide.placeholders[1].text = "Generated by META-COMPILER"

    # Content slides — split on heading markers
    sections: list[tuple[str, list[str]]] = []
    current_heading = "Content"
    current_lines: list[str] = []

    for line in text.split("\n"):
        stripped = line.strip()
        if stripped.startswith("# ") or stripped.startswith("## "):
            if current_lines:
                sections.append((current_heading, current_lines))
            current_heading = stripped.lstrip("# ").strip()
            current_lines = []
        elif stripped:
            current_lines.append(stripped)
    if current_lines:
        sections.append((current_heading, current_lines))

    for heading, bullets in sections:
        slide = prs.slides.add_slide(prs.slide_layouts[1])
        slide.shapes.title.text = heading
        tf = slide.placeholders[1].text_frame
        tf.clear()
        for i, bullet in enumerate(bullets[:8]):  # limit bullets per slide
            para = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            para.text = bullet
            para.level = 0

    prs.save(str(path))


def write_pdf(path: Path, text: str, title: str) -> None:
    """Write text into a .pdf document."""
    import fitz  # PyMuPDF

    doc = fitz.open()
    page = doc.new_page()
    # Insert title
    title_rect = fitz.Rect(72, 72, page.rect.width - 72, 120)
    page.insert_textbox(title_rect, title, fontsize=18, fontname="helv")

    # Split text into lines and paginate manually for reliability
    lines = text.split("\n")
    line_height = 14  # approximate for fontsize=10
    margin_top = 130
    margin_bottom = 72
    usable_height = page.rect.height - margin_top - margin_bottom
    lines_per_page = max(1, int(usable_height / line_height))

    # First page starts after title
    current_lines = lines[:lines_per_page]
    remaining_lines = lines[lines_per_page:]

    body_rect = fitz.Rect(72, margin_top, page.rect.width - 72, page.rect.height - margin_bottom)
    page.insert_textbox(body_rect, "\n".join(current_lines), fontsize=10, fontname="helv")

    # Additional pages
    max_pages = 200
    pages_created = 1
    full_page_lines = max(1, int((page.rect.height - 72 - 72) / line_height))

    while remaining_lines and pages_created < max_pages:
        page = doc.new_page()
        pages_created += 1
        current_lines = remaining_lines[:full_page_lines]
        remaining_lines = remaining_lines[full_page_lines:]
        body_rect = fitz.Rect(72, 72, page.rect.width - 72, page.rect.height - 72)
        page.insert_textbox(body_rect, "\n".join(current_lines), fontsize=10, fontname="helv")

    doc.save(str(path))
    doc.close()


WRITERS = {
    ".docx": write_docx,
    ".xlsx": write_xlsx,
    ".pptx": write_pptx,
    ".pdf": write_pdf,
}


def write_document(path: Path, text: str, title: str = "Document") -> None:
    """Write text content to a document file."""
    suffix = path.suffix.lower()
    writer = WRITERS.get(suffix)
    if writer is None:
        raise ValueError(
            f"Unsupported output format: {suffix}. "
            f"Supported formats: {', '.join(sorted(WRITERS))}"
        )
    path.parent.mkdir(parents=True, exist_ok=True)
    writer(path, text, title)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Write text content to documents (docx, xlsx, pptx, pdf)."
    )
    parser.add_argument("output", help="Output file path (.docx, .xlsx, .pptx, .pdf)")
    parser.add_argument(
        "--input", "-i",
        default=None,
        help="Read text from this file instead of stdin",
    )
    parser.add_argument(
        "--title", "-t",
        default="Document",
        help="Document title (default: Document)",
    )
    args = parser.parse_args(argv)

    if args.input:
        text = Path(args.input).read_text(encoding="utf-8")
    else:
        text = sys.stdin.read()

    output_path = Path(args.output)
    try:
        write_document(output_path, text, title=args.title)
    except Exception as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1

    print(f"Document written to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
